#!/bin/bash
echo "=== TEST VARIABILI UNIVERSALI ==="
echo "Utente corrente: $(whoami)"
echo "UID corrente: $(id -u)"
echo "Home corrente: $HOME"
echo ""
echo "=== TEST ESPANSIONE VARIABILI ==="
TARGET_USER="$(whoami)"
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
XDG_RUNTIME_DIR="/run/user/$(id -u)"
XAUTHORITY="$HOME/.Xauthority"
OLMS_HOME="$HOME/.olms"
OLMS_PROJECT_DIR="$HOME/Progetti/OLMS-Core"

echo "TARGET_USER: $TARGET_USER"
echo "DBUS_SESSION_BUS_ADDRESS: $DBUS_SESSION_BUS_ADDRESS"
echo "XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR"
echo "XAUTHORITY: $XAUTHORITY"
echo "OLMS_HOME: $OLMS_HOME"
echo "OLMS_PROJECT_DIR: $OLMS_PROJECT_DIR"
echo ""
echo "✅ Tutte le variabili sono state espandite correttamente!"
