@audio          -       rtprio          99
@audio          -       memlock         unlimited
francesco_ssh   -       rtprio          99
francesco_ssh   -       memlock         unlimited
root            -       rtprio          99
root            -       memlock         unlimited
